### ISSUE TITLE
Deal with Zotero Element set when uninstalling/reinstalling

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-ZoteroImport#5]
From the forums http://omeka.org/forums/topic/zotero-import-stopped-importing#post-111738

```
After uninstalling, the Zotero record is not deleted from the omeka_element_set table; you'll get an error when trying to reinstall. One needs to delete the Zotero record from omeka_element_set before reinstallation.
```

Should the element set be deleted, which would kill a lot of data, or should the plugin just check to see if Zotero elements are already there?

**Comment by jimsafley** [comment]
While I don't think the plugin should delete the element set when uninstalled, I suppose it could, during installation, assume that an existing "Zotero" element set is valid. Right now if "Zotero" exists it refuses to be installed.

**Comment by patrickmj** [comment]
yeah, I lean toward doing the check on (re)installation

**Comment by jimsafley** [comment]
On second thought, I don't want to assume that an existing "Zotero" element set is valid, nor do I think it's worth the time to check every "Zotero" element against a list prior to installation. I think the existing fail-safe is sufficient.
